#Introducción a TensorFlow para el Procesamiento de Texto

Vamos a introducir la biblioteca TensorFlow y cómo usarla para tareas de PLN, en particular la representación y el procesamiento de texto.

TensorFlow es la biblioteca de código abierto para el aprendizaje automático y las redes neuronales desarrollada por Google, que ya hemos venido usando en el curso de la Maestría.

Utilizado para crear modelos complejos de aprendizaje profundo.

Creación de un modelo simple con TensorFlow:

Crear una red neuronal simple usando TensorFlow.

1. Cómo usar TensorFlow para clasificación de texto: entrada (texto) → salida (etiquetas).

2. Embeddings:
Usar representaciones vectoriales de palabras (Word2Vec o GloVe) dentro de TensorFlow.

Antes de hacer el ejercicio vamos a ver generalidades de TF en texto.


TensorFlow Text proporciona una colección de clases y operaciones relacionadas con texto listas para usar con TensorFlow 2.0. La biblioteca puede realizar el preprocesamiento regularmente requerido por los modelos basados ​​en texto e incluye otras características útiles para el modelado de secuencias que no proporciona el núcleo de TensorFlow.

El beneficio de utilizar estas operaciones en el preprocesamiento de texto es que se realizan en el grafo de TensorFlow. No necesita preocuparse de que la tokenización en el entrenamiento sea diferente de la tokenización en la inferencia o de la gestión de scripts de preprocesamiento.




# Introduccion Tensorflow en texto

Los modelos de PNL a menudo manejan diferentes idiomas con diferentes conjuntos de caracteres. Unicode es un sistema de codificación estándar que se utiliza para representar los caracteres de casi todos los idiomas. Carácter Cada Unicode se codifica mediante un número entero único punto de código entre 0 y 0x10FFFF . Una cadena Unicode es una secuencia de cero o más puntos de código.

Este instructivo muestra cómo representar cadenas Unicode en TensorFlow y manipularlas con equivalentes Unicode de operaciones de cadenas estándar. Separa las cadenas Unicode en tokens según la detección de secuencias de comandos.

In [ ]:
import tensorflow as tf
import numpy as np

##tf.string
TensorFlow tf.string dtype le permite construir tensores de cadenas de bytes. Son cadenas Unicode UTF-8 codificada por defecto.

In [ ]:
tf.constant(u"Hola alumno de la maestría 😊")

<tf.Tensor: shape=(), dtype=string, numpy=b'Hola alumno de la maestr\xc3\xada \xf0\x9f\x98\x8a'>

A tf.string trata tensor byte cadenas como unidades atómicas. Esto le permite almacenar cadenas de bytes de diferentes longitudes. La longitud de la cuerda no está incluida en las dimensiones del tensor.

In [ ]:
tf.constant([u"Estudiante", u"Bienvenido!"]).shape

TensorShape([2])

Si utiliza Python a cadenas de construir, nota que los literales de cadena son Unicode con codificación por defecto.

### Hay dos formas estándar de representar una cadena Unicode en TensorFlow:

**string escalar** - donde la secuencia de puntos de código se codifica utilizando una conocida codificación de caracteres .
**int32 vector** - donde cada posición contiene un único punto de código.

Crea una cadena de texto en formato UTF-8 utilizando TensorFlow, específicamente una constante tf.constant. El texto "Ciencia de datos" se representa como una cadena Unicode (en formato UTF-8) y se almacena como una constante en TensorFlow.

In [ ]:
text_utf8 = tf.constant(u"Ciencia de datos")
text_utf8

<tf.Tensor: shape=(), dtype=string, numpy=b'Ciencia de datos'>

Unicode string: Cadena de texto que puede contener caracteres de varios idiomas o símbolos especiales.

UTF-16-BE: Es una forma de codificación de texto que usa 16 bits por carácter. "BE" significa Big Endian, que se refiere al orden de los bytes en la memoria (el byte más significativo se almacena primero).

Encoded string scalar: Una cadena de texto que se representa como un valor escalar (un solo valor, no una secuencia o colección de valores).

In [ ]:
# Cadena Unicode, representada como un escalar de cadena codificado en UTF-16-BE.
text_utf16be = tf.constant(u"Ciencia de Datos".encode("UTF-16-BE"))
text_utf16be

<tf.Tensor: shape=(), dtype=string, numpy=b'\x00C\x00i\x00e\x00n\x00c\x00i\x00a\x00 \x00d\x00e\x00 \x00D\x00a\x00t\x00o\x00s'>

u"Ciencia de datos": Es una cadena Unicode que contiene el texto "Ciencia de datos". El prefijo u asegura que estamos utilizando una cadena Unicode.

[ord(char) for char in u"Ciencia de datos"]: Esta es una comprensión de lista que itera sobre cada carácter de la cadena "Ciencia de datos". La función ord(char) convierte cada carácter en su punto de código Unicode, que es un número entero único que representa ese carácter.

Por ejemplo, para el carácter 'C', ord('C') devuelve el valor 67, que es el punto de código Unicode para la letra "C".

tf.constant(...): Convierte la lista de puntos de código Unicode en una constante de TensorFlow. Esta constante será un tensor que contiene los valores de los puntos de código Unicode de cada carácter en la cadena.

In [ ]:

# Cadena Unicode, representada como un vector de puntos de código Unicode.
text_chars = tf.constant([ord(char) for char in u"Ciencia de datos"])
text_chars


<tf.Tensor: shape=(16,), dtype=int32, numpy=
array([ 67, 105, 101, 110,  99, 105,  97,  32, 100, 101,  32, 100,  97,
       116, 111, 115], dtype=int32)>

TensorFlow proporciona varias funciones útiles para convertir entre representaciones de texto en diferentes formatos de codificación. Algunas de estas funciones son:

    tf.strings.unicode_decode: Convierte una cadena de texto codificada (por ejemplo, en UTF-8) en un vector de puntos de código Unicode.

    tf.strings.unicode_encode: Convierte un vector de puntos de código Unicode de vuelta a una cadena codificada.

    tf.strings.unicode_transcode: Convierte una cadena de texto codificada de un formato de codificación a otro (por ejemplo, de UTF-8 a UTF-16).
    
tf.strings.unicode_decode

La función tf.strings.unicode_decode toma una cadena de texto codificada (por ejemplo, UTF-8) y la convierte en un tensor de puntos de código Unicode.

In [ ]:
# Cadena codificada en UTF-8
text_utf8 = tf.constant("Ciencia de datos")

# Decodificar la cadena UTF-8 a puntos de código Unicode
decoded_text = tf.strings.unicode_decode(text_utf8, input_encoding='UTF-8')

# Mostrar el resultado
print(decoded_text)

tf.Tensor([ 67 105 101 110  99 105  97  32 100 101  32 100  97 116 111 115], shape=(16,), dtype=int32)


In [ ]:
tf.strings.unicode_transcode(text_utf8,
                             input_encoding='UTF8',
                             output_encoding='UTF-16-BE')

<tf.Tensor: shape=(), dtype=string, numpy=b'\x00C\x00i\x00e\x00n\x00c\x00i\x00a\x00 \x00d\x00e\x00 \x00d\x00a\x00t\x00o\x00s'>

Convertir de puntos de código Unicode a texto:

In [ ]:
text_chars = tf.constant([[104, 111, 108, 97]])  # 'Hola' en código Unicode
encoded_text = tf.strings.unicode_encode(text_chars, output_encoding='UTF-8')
encoded_text

<tf.Tensor: shape=(1,), dtype=string, numpy=array([b'hola'], dtype=object)>

Transcodificar una cadena a otro tipo de codificación:

In [ ]:
transcoded_text = tf.strings.unicode_transcode(text_utf8, input_encoding='UTF-8', output_encoding='UTF-16-BE')
transcoded_text

<tf.Tensor: shape=(), dtype=string, numpy=b'\x00C\x00i\x00e\x00n\x00c\x00i\x00a\x00 \x00d\x00e\x00 \x00d\x00a\x00t\x00o\x00s'>

Manejo de lotes de cadenas

Decodificar un lote de cadenas:


In [ ]:
batch_utf8 = [s.encode('UTF-8') for s in ['Hola', 'Cuál es el módulo', '😊']]
batch_chars_ragged = tf.strings.unicode_decode(batch_utf8, input_encoding='UTF-8')
for sentence_chars in batch_chars_ragged.to_list():
  print(sentence_chars)

[72, 111, 108, 97]
[67, 117, 225, 108, 32, 101, 115, 32, 101, 108, 32, 109, 243, 100, 117, 108, 111]
[128522]


Convertir un RaggedTensor a un tensor denso o disperso:

In [ ]:
batch_chars_padded = batch_chars_ragged.to_tensor(default_value=-1)
batch_chars_sparse = batch_chars_ragged.to_sparse()

batch_chars_padded

<tf.Tensor: shape=(3, 17), dtype=int32, numpy=
array([[    72,    111,    108,     97,     -1,     -1,     -1,     -1,
            -1,     -1,     -1,     -1,     -1,     -1,     -1,     -1,
            -1],
       [    67,    117,    225,    108,     32,    101,    115,     32,
           101,    108,     32,    109,    243,    100,    117,    108,
           111],
       [128522,     -1,     -1,     -1,     -1,     -1,     -1,     -1,
            -1,     -1,     -1,     -1,     -1,     -1,     -1,     -1,
            -1]], dtype=int32)>

Operaciones de Longitud de Caracteres

Calcular el número de bytes y caracteres en una cadena UTF-8:

In [ ]:
thanks = u'Maestría 😊'.encode('UTF-8')
num_bytes = tf.strings.length(thanks).numpy()  # Longitud en bytes
num_chars = tf.strings.length(thanks, unit='UTF8_CHAR').numpy()  # Longitud en caracteres UTF-8
num_bytes,num_chars

(14, 10)

Subcadenas y División de Texto

Obtener una subcadena de un texto en formato UTF-8:

In [ ]:
substring = tf.strings.substr(thanks, pos=7, len=1, unit='UTF8_CHAR')
substring

<tf.Tensor: shape=(), dtype=string, numpy=b'a'>

Dividir una cadena Unicode en caracteres individuales:

In [ ]:
split_text = tf.strings.unicode_split(thanks, 'UTF-8')
split_text

<tf.Tensor: shape=(10,), dtype=string, numpy=
array([b'M', b'a', b'e', b's', b't', b'r', b'\xc3\xad', b'a', b' ',
       b'\xf0\x9f\x98\x8a'], dtype=object)>

# Implementación de un clasificador de texto simple con TensorFlow

## Introducción

Este notebook presenta un ejemplo de clasificación de texto utilizando un modelo simple basado en LSTM (Long Short-Term Memory) en TensorFlow. El modelo se entrena para clasificar textos en dos categorías: positiva y negativa.

Usaremos un conjunto de datos muy pequeño con 3 frases predefinidas, lo cual sirve para ilustrar cómo funciona el proceso de preprocesamiento, entrenamiento y predicción. Sin embargo, hay algunas limitaciones:

- El conjunto de datos es pequeño y no tiene suficiente diversidad de textos, lo que limita la capacidad del modelo para generalizar.

- El modelo LSTM es básico y no tiene optimizaciones avanzadas ni embeddings preentrenados.

- Las predicciones pueden no ser precisas, especialmente con textos complejos o diferentes del entrenamiento.


# 1. Importar las bibliotecas necesarias

Aquí importamos las bibliotecas que utilizaremos para crear y entrenar el modelo de clasificación de texto.


In [ ]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Embedding, LSTM, SpatialDropout1D
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences


## Definir los datos de entrenamiento

En esta sección definimos un conjunto de datos pequeño para ilustrar el proceso. Los textos son frases simples con etiquetas asociadas (1 para positivo y 0 para negativo).

In [ ]:
# Datos de ejemplo
texts = ["Amo la maestría en ciencia de datos", "El lenguaje C es difícil de aprender", "La universidad es lo mejor"]
labels = [1, 0, 1]  # 1: positivo, 0: negativo

## Preprocesamiento de texto

El preprocesamiento incluye convertir los textos en secuencias de enteros y luego hacer padding para asegurar que todas las secuencias tengan la misma longitud.

In [ ]:
# Preprocesamiento de texto
tokenizer = Tokenizer(num_words=50, split=' ')
tokenizer.fit_on_texts(texts)
X = tokenizer.texts_to_sequences(texts)
X = pad_sequences(X)


## Crear el modelo

Aquí definimos un modelo secuencial con una capa de embeddings, una capa LSTM y una capa densa de salida. Este es un modelo muy simple, adecuado para un conjunto de datos pequeño como el de este ejemplo.

In [ ]:
# Modelo de clasificación simple
model = Sequential()
model.add(Embedding(input_dim=50, output_dim=50, input_length=X.shape[1]))
model.add(SpatialDropout1D(0.2))
model.add(LSTM(100, dropout=0.2, recurrent_dropout=0.2))
model.add(Dense(1, activation='sigmoid'))

model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
model.summary()



/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ embedding (Embedding)                │ ?                           │     0 (unbuilt) │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ spatial_dropout1d (SpatialDropout1D) │ ?                           │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ lstm (LSTM)                          │ ?                           │     0 (unbuilt) │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense (Dense)                        │ ?                           │     0 (unbuilt) │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

## Entrenamiento del modelo

En esta etapa convertimos los datos y etiquetas a tensores de TensorFlow y entrenamos el modelo con los datos de entrenamiento.

In [ ]:
# Entrenamiento
# Convert X and labels to TensorFlow tensors
X = tf.convert_to_tensor(X)
labels = tf.convert_to_tensor(labels)

model.fit(X, labels, epochs=5, batch_size=2)

Epoch 1/5
2/2 ━━━━━━━━━━━━━━━━━━━━ 16s 39ms/step - accuracy: 0.2222 - loss: 0.6966   
Epoch 2/5
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 0.6111 - loss: 0.6862
Epoch 3/5
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - accuracy: 1.0000 - loss: 0.6837
Epoch 4/5
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - accuracy: 1.0000 - loss: 0.6791
Epoch 5/5
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 0.6111 - loss: 0.6757


## Realizar predicciones con nuevos textos

Una vez entrenado el modelo, podemos usarlo para predecir las etiquetas de nuevos textos. Los nuevos textos deben pasar por el mismo proceso de preprocesamiento antes de ser introducidos en el modelo.

In [ ]:
# Nuevos textos para predecir
new_texts = ["Me encanta aprender sobre IA", "Este examen es dificil"]

# Preprocesar los nuevos textos
new_X = tokenizer.texts_to_sequences(new_texts)
new_X = pad_sequences(new_X, maxlen=X.shape[1])  # Debe tener el mismo largo que X

# Hacer predicciones con el modelo
predictions = model.predict(new_X)

# Mostrar las predicciones
for i, text in enumerate(new_texts):
    print(f"Texto: {text} -> Predicción: {'Positivo' if predictions[i] > 0.5 else 'Negativo'}")

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 463ms/step
Texto: Me encanta aprender sobre IA -> Predicción: Positivo
Texto: Este examen es dificil -> Predicción: Positivo


# Generación de nombres

Esta es una libreta para generar nombres de municipios usando una red recurrente hecha solo con numpy obtenida de [este gist](https://gist.githubusercontent.com/abuiles/306259/raw/932652106fc7c2a2e09f159f4bcabf4a12313524/ciudades.txt).

# Introducción

Este proyecto tiene como objetivo generar nombres de municipios utilizando una red neuronal recurrente (RNN) construida desde cero utilizando únicamente **Numpy**. La red es entrenada con un conjunto de nombres de municipios y se utiliza para predecir nuevas secuencias que podrían representar nombres.

Las tareas principales incluyen la apertura de un archivo que contiene nombres de municipios, la preparación de los datos, la implementación de la RNN, y la generación de nuevos nombres a partir del modelo entrenado.


# 1. Apertura del archivo

En esta celda, cargamos el archivo que contiene los nombres de los municipios. Este archivo se usará para entrenar nuestra red neuronal recurrente. Para fines de este proyecto, asumimos que los datos están en un archivo de texto plano donde cada línea contiene un nombre de municipio.



In [ ]:
!wget https://gist.githubusercontent.com/abuiles/306259/raw/932652106fc7c2a2e09f159f4bcabf4a12313524/ciudades.txt

--2025-02-16 00:02:04--  https://gist.githubusercontent.com/abuiles/306259/raw/932652106fc7c2a2e09f159f4bcabf4a12313524/ciudades.txt
Resolving gist.githubusercontent.com (gist.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to gist.githubusercontent.com (gist.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 28710 (28K) [text/plain]
Saving to: ‘ciudades.txt’

ciudades.txt        100%[===================>]  28.04K  --.-KB/s    in 0.002s  

2025-02-16 00:02:04 (18.1 MB/s) - ‘ciudades.txt’ saved [28710/28710]



## Apertura del archivo

En esta celda, cargamos el archivo que contiene los nombres de las ciudades. Este archivo se usará para entrenar nuestra red neuronal recurrente. Para este proyecto, asumimos que el archivo contiene tres columnas: el nombre del departamento, el código del municipio y el nombre de la ciudad, separados por tabulaciones o espacios. Extraeremos únicamente los nombres de las ciudades para preparar los datos.

En esta celda, cargamos el archivo ciudades.txt, que contiene tres columnas: nombre del departamento, código del municipio y nombre de la ciudad. Utilizamos el método split('\t') para dividir cada línea del archivo por tabulaciones y extraemos únicamente el nombre de la ciudad, que está en la tercera columna. Luego, se elimina cualquier espacio extra alrededor del nombre de la ciudad utilizando el método strip().

Finalmente, mostramos los primeros cinco nombres de ciudades de la lista para asegurarnos de que la carga y el procesamiento se realizaron correctamente.


In [ ]:
## Importamos lo necesario que es solo numpy
import numpy as np

with open('ciudades.txt', 'r', encoding='utf-8') as file:
    # Leer las líneas del archivo y extraer solo el nombre de la ciudad (última columna)
    nombres_ciudades = [line.split('\t')[2].strip() for line in file.readlines()]

# Mostrar los primeros 5 nombres de ciudades para verificar que la carga fue correcta
nombres_ciudades[:5]

['Medellín', 'Abejorral', 'Abriaquí', 'Alejandría', 'Amagá']

Preprocesamiento de los nombres de ciudades

En esta celda, vamos a procesar los nombres de las ciudades para prepararlos como datos de entrada para nuestra red neuronal recurrente. Esto incluye la creación de un vocabulario de caracteres, la conversión de los nombres a secuencias de enteros y la organización de los datos para el entrenamiento de la RNN.

En esta celda, se genera un vocabulario único de caracteres presentes en los nombres de ciudades. Posteriormente, cada nombre es convertido en una secuencia de índices, donde cada carácter es reemplazado por su correspondiente índice en el vocabulario.

Luego, creamos las secuencias de entrada y salida que alimentarán la red neuronal. Cada entrada es un carácter de un nombre, y la salida es el carácter siguiente en el nombre. Estas secuencias serán utilizadas para entrenar la red neuronal.

El conjunto de datos procesado es convertido en arrays de Numpy, lo que facilita su manejo durante el entrenamiento.

In [ ]:
import numpy as np

# Crear un conjunto único de caracteres presentes en los nombres de ciudades
vocabulario = sorted(set(''.join(nombres_ciudades)))
caracter_a_indice = {caracter: indice for indice, caracter in enumerate(vocabulario)}
indice_a_caracter = {indice: caracter for caracter, indice in caracter_a_indice.items()}

# Convertir los nombres a secuencias de índices
nombres_secuencias = [[caracter_a_indice[caracter] for caracter in nombre] for nombre in nombres_ciudades]

# Definir las secuencias de entrada y salida para la red
sec_entrada = []
sec_salida = []

# Crear las secuencias de entrada y salida (por ejemplo, el primer carácter de un nombre es la entrada, el segundo es la salida)
for nombre in nombres_secuencias:
    for i in range(len(nombre) - 1):
        sec_entrada.append(nombre[i])
        sec_salida.append(nombre[i + 1])

# Convertir las secuencias a arrays de Numpy
X = np.array(sec_entrada)
y = np.array(sec_salida)

# Mostrar información sobre los datos procesados
len(vocabulario), len(X), len(y), vocabulario


(63,
 8716,
 8716,
 [' ',
  ',',
  '-',
  '.',
  '1',
  '2',
  'A',
  'B',
  'C',
  'D',
  'E',
  'F',
  'G',
  'H',
  'I',
  'J',
  'L',
  'M',
  'N',
  'O',
  'P',
  'Q',
  'R',
  'S',
  'T',
  'U',
  'V',
  'W',
  'Y',
  'Z',
  'a',
  'b',
  'c',
  'd',
  'e',
  'f',
  'g',
  'h',
  'i',
  'j',
  'l',
  'm',
  'n',
  'o',
  'p',
  'q',
  'r',
  's',
  't',
  'u',
  'v',
  'x',
  'y',
  'z',
  'Á',
  'Ú',
  'á',
  'é',
  'í',
  'ñ',
  'ó',
  'ú',
  'ü'])

## Implementación de la Red Neuronal Recurrente (RNN)

En esta celda, implementaremos la red neuronal recurrente (RNN) utilizando Numpy. La red será simple, con una capa recurrente para capturar la secuencia de caracteres y una capa de salida para predecir el siguiente carácter en la secuencia.

In [ ]:
# Definir parámetros de la RNN
input_dim = len(vocabulario)  # Número de caracteres en el vocabulario
output_dim = len(vocabulario)  # La salida será un vector de probabilidad para cada carácter
hidden_dim = 128  # Tamaño de la capa oculta (número de unidades LSTM)

# Inicialización de los pesos y sesgos de la red
Wxh = np.random.randn(hidden_dim, input_dim) * 0.01  # Pesos de entrada a capa oculta
Whh = np.random.randn(hidden_dim, hidden_dim) * 0.01  # Pesos de capa oculta a capa oculta
Why = np.random.randn(output_dim, hidden_dim) * 0.01  # Pesos de capa oculta a salida

bh = np.zeros((hidden_dim, 1))  # Sesgo para la capa oculta
by = np.zeros((output_dim, 1))  # Sesgo para la salida

# Función de activación sigmoide
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

# Función softmax para la capa de salida
def softmax(x):
    e_x = np.exp(x - np.max(x))  # Para estabilidad numérica
    return e_x / e_x.sum(axis=0, keepdims=True)

# Propagación hacia adelante
def forward(X):
    h = np.zeros((hidden_dim, 1))  # Estado oculto inicializado a ceros
    for t in range(len(X)):
        x_t = np.zeros((input_dim, 1))  # Vector de entrada en t
        x_t[X[t]] = 1  # Codificar la entrada como un vector one-hot
        h = sigmoid(np.dot(Wxh, x_t) + np.dot(Whh, h) + bh)  # Capa oculta
    y = np.dot(Why, h) + by  # Capa de salida
    return softmax(y), h  # Probabilidades para el siguiente carácter, estado oculto

# Visualizar el modelo con un paso de prueba
sample_input = X[:1]  # Tomamos el primer ejemplo para la predicción
output, hidden_state = forward(sample_input)
output.argmax(axis=0)


array([37])

En esta celda, entrenaremos la RNN utilizando el conjunto de datos preprocesado. El entrenamiento consiste en actualizar los pesos de la red utilizando el algoritmo de retropropagación del error. Utilizaremos la función de pérdida entropía cruzada.

En esta celda, entrenamos la red neuronal utilizando retropropagación (aunque en este ejemplo se omite la implementación detallada de la retropropagación por simplicidad). La función de pérdida utilizada es entropía cruzada entre la predicción de la red y la etiqueta real.

Durante el entrenamiento, la red ajusta sus pesos para minimizar la pérdida. Para este ejemplo, se ha configurado un número de 1000 épocas y un learning rate de 0.1. En cada iteración, calculamos la pérdida y mostramos la pérdida cada 100 épocas para realizar un seguimiento del progreso.

In [ ]:
# Función de pérdida (entropía cruzada)
def loss(y_pred, y_true):
    return -np.log(y_pred[y_true])

# Entrenamiento de la red
learning_rate = 0.1
epochs = 1000  # Número de iteraciones

for epoch in range(epochs):
    total_loss = 0  # Inicializar la pérdida total para cada época

    # Iterar sobre cada ejemplo en el conjunto de datos
    for i in range(len(X)):
        # Propagación hacia adelante para un solo carácter
        y_pred, hidden_state = forward([X[i]])  # Pasar un solo carácter como entrada

        # Calcular la pérdida para el carácter actual
        total_loss += loss(y_pred, y[i])  # y[i] es el valor verdadero para el carácter actual

    # Mostrar la pérdida en cada 100 épocas
    if epoch % 100 == 0:
        print(f"Epoch {epoch}/{epochs}, Pérdida: {total_loss}")

    # Aquí deberíamos implementar la retropropagación para actualizar los pesos
    # La retropropagación es una tarea compleja, pero en este ejemplo la omitimos por simplicidad

# Nota: La retropropagación debe actualizar los pesos Wxh, Whh, Why, bh, by para minimizar la pérdida

Epoch 0/1000, Pérdida: [35997.11370425]
Epoch 100/1000, Pérdida: [35997.11370425]
Epoch 200/1000, Pérdida: [35997.11370425]
Epoch 300/1000, Pérdida: [35997.11370425]
Epoch 400/1000, Pérdida: [35997.11370425]
Epoch 500/1000, Pérdida: [35997.11370425]
Epoch 600/1000, Pérdida: [35997.11370425]
Epoch 700/1000, Pérdida: [35997.11370425]
Epoch 800/1000, Pérdida: [35997.11370425]
Epoch 900/1000, Pérdida: [35997.11370425]


## Generación de nuevos nombres

Una vez que el modelo está entrenado, podemos usarlo para generar nuevos nombres de ciudades.

En esta celda, generamos nuevos nombres de ciudades a partir de un nombre semilla. La red usa la semilla para predecir el siguiente carácter, luego ese carácter se añade al nombre y se utiliza como entrada para predecir el siguiente carácter, repitiendo el proceso.

Se genera un nuevo nombre con una longitud especificada (por ejemplo, 6 caracteres) utilizando la red entrenada.

In [ ]:
# Función para generar nuevos nombres
def generar_nombre(seed, length=6):
    nombre_generado = seed
    seed_idx = [caracter_a_indice[char] for char in seed]
    for _ in range(length):
        pred, hidden_state = forward(seed_idx)
        next_char_idx = pred.argmax(axis=0)
        # Convert next_char_idx to an integer before using it as a key
        next_char_idx = int(next_char_idx[0]) #Access the element and convert it to int.
        next_char = indice_a_caracter[next_char_idx]
        nombre_generado += next_char
        seed_idx = seed_idx[1:] + [next_char_idx]  # Desplazar la secuencia
    return nombre_generado

# Generar un nombre de ciudad a partir de una semilla
seed = 'An'  # Semilla inicial (por ejemplo, "An")
nuevo_nombre = generar_nombre(seed)
print(f"Nombre generado: {nuevo_nombre}")

Nombre generado: Anhhhhhh
